# What is NumPy?
NumPy is a Python library used for working with arrays.<br>
-->It also has functions for working in domain of linear algebra, fourier transform, and matrices.<br>
-->NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.<br>
-->NumPy stands for Numerical Python.

Array, Arange, Zeros, Ones, Linspace, Eye, Random

In [2]:
import numpy as np

#Array()
a=np.array([1,2,3,4,5])
print('Array ',a)

#Arange()
b=np.arange(1,10,2)
print('Arange ',b)

#Zeros()--zeros(shape, dtype=float, order='c')
print('Zeros ', np.zeros(10, dtype=float, order='F'))

#ones()--ones(shape, dtype=None, order='c')
print('ones ',np.ones(5))

#Linspace()--linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)
print('Linspace ',np.linspace(1.0, 3.0, num=5, retstep=True, endpoint=False))
print(np.linspace(1, 100, num=50, retstep=True))

#Eye()--eye(R(row), C(col)=None, k = 0, dtype=None, order='c')
print('Eye ',np.eye(4,5,k=2)) 

#Random--random.rand(R,C) or rand()-uniformly distribute value(+), randn()-Normally distribute value(+,-), ranf(), randint()
print('rand() ',np.random.rand(3,2))
print('randn() ',np.random.randn(3,2))
print('ranf() ',np.random.ranf(3))
print('randint() ',np.random.randint(3))

Array  [1 2 3 4 5]
Arange  [1 3 5 7 9]
Zeros  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones  [1. 1. 1. 1. 1.]
Linspace  (array([1. , 1.4, 1.8, 2.2, 2.6]), 0.4)
(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ]), 2.020408163265306)
Eye  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1.

## Attributes of Array
1.Dimension - ndim<br>
2.Shape - a.shape<br>
3.Size - a.size<br>
4.Datatype - a.dtype<br>
5.Itemsize - a.itemsize.

In [3]:
import numpy as np
att = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(att.ndim)
print(att.shape)
print(att.size)
print(att.dtype)
print(att.itemsize)

2
(2, 5)
10
int32
4


## Data Types
Numerical Datatype:<br>
*Boolean - (bool) - np.bool_ - '?' <br>
*Integer - (int) - np.int_ - 'i' <br>
*Float - (float) - np.float_ - 'f' <br>
*Complex- (bool) - np.complex_ <br>
*Unsigned integer - 'u' <br>
*Byte - 'b' <br>
*Unsingned bytes - 'B'

In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1.dtype)
arr2=np.zeros(5,dtype='f')
print(arr2.dtype)

#Two ways to convert datatype
print('int32 - float :',arr1.astype(float))
print('float32 - int32 :',np.int32(arr2))

int32
float32
int32 - float : [1. 2. 3. 4. 5.]
float32 - int32 : [0 0 0 0 0]


## Slicing
1D - name [start:end:step] <br>
2D - name [start:end:step, start:end:step] - [i(row),j(col)] <br>
3D - name [start:end:step, start:end:step, start:end:step] - [i(no.of array),j(row),k(col)] 

In [5]:
#1D 
import numpy as np
arr3=np.array([1, 2, 3, 4, 5, 6, 7])
print('Index 1 to index 5 ',arr3[1:5]) 
print('Index 4 to the end of the array ',arr3[4:])
print('Beginning to index 4 (not included) ',arr3[:4])
#Negative Slicing
print('Index 3 from the end to index 1 ',arr3[-3:-1])
print('Element from index 1 to index 5 ',arr3[1:5:2])
print('Return every other element from the entire array ',arr3[::2])


Index 1 to index 5  [2 3 4 5]
Index 4 to the end of the array  [5 6 7]
Beginning to index 4 (not included)  [1 2 3 4]
Index 3 from the end to index 1  [5 6]
Element from index 1 to index 5  [2 4]
Return every other element from the entire array  [1 3 5 7]


In [6]:
#2D
import numpy as np
arr4=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr4[1, 1:4]) #From the second element, slice elements from index 1 to index 4 (not included)
print(arr4[0:2, 2]) #From both elements, return index 2
print(arr4[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## Array Indexing
-->Array indexing is the same as accessing an array element.<br>
-->You can access an array element by referring to its index number.<br>
-->The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [7]:
import numpy as np
#Access 1-D Arrays
index=np.arange(1,10)
print('Range of numbers 1 to 9: ',index)
print('Get the first element: ',index[0])
print('Get the second element: ',index[1])
print('Get third and fourth elements: ',index[3]+index[4])
arr5=np.array([1,4,5])
print('Access index from another array: ',index[arr5])

#Access 2-D Arrays
arr6 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr6[0, 1])
print('5th element on 2nd dim: ', arr6[1, 4])

#Access 3-D Arrays
arr7 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('3D array indexing: ',arr7[0, 1, 2])

#Negative Indexing
print('Last element from 2nd dim: ', arr6[1, -1])

Range of numbers 1 to 9:  [1 2 3 4 5 6 7 8 9]
Get the first element:  1
Get the second element:  2
Get third and fourth elements:  9
Access index from another array:  [2 5 6]
2nd element on 1st dim:  2
5th element on 2nd dim:  10
3D array indexing:  6
Last element from 2nd dim:  10


## Arithmetic Operator
-->Using scalar - constant element to an array <br>
-->Between two array - Add two array or multiply <br>
Notes:<br>
1. a+b =>np.add(a,b) <br>
2. a-b =>np.subtract(a,b) <br>
3. a*b =>np.multiply(a,b) <br>
4. a/b =>np.divide(a,b) <br>
5. a%b =>np.mod(a,b) <br>
6. a**b =>np.power(a,b)

In [8]:
import numpy as np
#1D Operation
op_scalar_one = np.arange(1,5)
print('Addition scalar one: ',op_scalar_one +3)
print('Multiplication scalar one: ',op_scalar_one *3)

#2D Operation
op_scalar_two=np.array([[1,2],[3,4]])
op_two_array=np.array([[5,6],[7,3]])
print('Addition scalar two:  ',op_scalar_two + 2)
print('Multiplication scalar two: ',op_scalar_two * 2)
print('Addition two array:  ',op_scalar_two + op_two_array)
print('Multiplication two array:  ',op_scalar_two * op_two_array)

Addition scalar one:  [4 5 6 7]
Multiplication scalar one:  [ 3  6  9 12]
Addition scalar two:   [[3 4]
 [5 6]]
Multiplication scalar two:  [[2 4]
 [6 8]]
Addition two array:   [[ 6  8]
 [10  7]]
Multiplication two array:   [[ 5 12]
 [21 12]]


## Broadcasting Rule
Numpy treats arrays with different shapes during arithmetic operations. <br>
Rule: <br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when<br>
1). they are equal, or <br>
2). one of them is 1

In [9]:
import numpy as np
aa=np.array([[1,2],[3,4],[5,6]])
bb=np.array([1,2,3])
cc=np.array([10,20])
dd=np.array([[1],[2],[3]])
ee=np.array([0])

print('aa ndim & shape: ',aa.ndim, aa.shape)
print('bb ndim & shape: ',bb.ndim, bb.shape)
print('cc ndim & shape: ',cc.ndim, cc.shape)
print('dd ndim & shape: ',dd.ndim, dd.shape)

print('aa(3,2) & cc(2,1) : ',aa*cc)
print('aa(3,2) & dd(3,1) : ',aa*dd)
print('bb(3,2) & dd(3,1) : ',bb*dd)

aa ndim & shape:  2 (3, 2)
bb ndim & shape:  1 (3,)
cc ndim & shape:  1 (2,)
dd ndim & shape:  2 (3, 1)
aa(3,2) & cc(2,1) :  [[ 10  40]
 [ 30  80]
 [ 50 120]]
aa(3,2) & dd(3,1) :  [[ 1  2]
 [ 6  8]
 [15 18]]
bb(3,2) & dd(3,1) :  [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [10]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print('x: \n',x)
print('xx: \n',xx)
print('y: \n',y)
print('z: \n',z)

print('\nx ndim & shape: ',x.ndim, x.shape)
print('xx ndim & shape: ',xx.ndim, xx.shape)
print('y ndim & shape: ',y.ndim, y.shape)
print('z ndim & shape: ',z.ndim, z.shape)

print('\nxx + y shape: ',(xx + y).shape)
print('Adding xx+y: \n',(xx + y))
print('\nx + z shape',(x + z).shape)
print('Adding x+z: \n',(x + z))

x: 
 [0 1 2 3]
xx: 
 [[0]
 [1]
 [2]
 [3]]
y: 
 [1. 1. 1. 1. 1.]
z: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

x ndim & shape:  1 (4,)
xx ndim & shape:  2 (4, 1)
y ndim & shape:  1 (5,)
z ndim & shape:  2 (3, 4)

xx + y shape:  (4, 5)
Adding xx+y: 
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]

x + z shape (3, 4)
Adding x+z: 
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## Array Manipulation
* Reshaping array <br>
* Array Flattening <br>
* Dimension Shuffling <br>
* Joining array <br>
* Splitting array <br>
* Add/Remove elements

### **Reshaping array**
* reshape()<br>
    ->Reshaping means changing the shape of an array.<br>
    ->The shape of an array is the number of elements in each dimension.<br>
    ->By reshaping we can add or remove dimensions or change number of elements in each dimension.<br>
 **(numpy.reshape(array, shape, order='c'))**--'C'=row, 'F'=col, 'A'=fortran 


* resize()<br>
 **(numpy.resize(array,shape))**

In [11]:
#reshape()
import numpy as np
ar1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#Reshape From 1-D to 2-D
newarr1 = ar1.reshape(4, 3)
print('Reshape From 1-D to 2-D: \n',newarr1)

#Reshape From 1-D to 2-D
newarr2 = ar1.reshape(2, 3, 2)
print('Reshape From 1-D to 3-D: \n',newarr2)

#Returns Copy or View?
ar3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print('Returns Copy or View: \n',ar3.reshape(2, 4).base)

#Unknown Dimension--use last at -1
newarr3 = ar3.reshape(2, 2, -1)
print('Unknown Dimension: \n',newarr3)
newarr4 = ar3.reshape(2, -1)
print('Unknown Dimension: \n',newarr4)

Reshape From 1-D to 2-D: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshape From 1-D to 3-D: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Returns Copy or View: 
 [1 2 3 4 5 6 7 8]
Unknown Dimension: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Unknown Dimension: 
 [[1 2 3 4]
 [5 6 7 8]]


In [12]:
#resize
import numpy as np
a1=np.arange(5)
print('Range of values: ',a1)
print('Resize the elements of 2 & 3: \n',np.resize(a1,(3,3)))

Range of values:  [0 1 2 3 4]
Resize the elements of 2 & 3: 
 [[0 1 2]
 [3 4 0]
 [1 2 3]]


### **Array Flattening**
* flatten()<br>
 **(numpy.flatten(order='c'))**--'C'=row, 'F'=col, 'A'=fortran , 'K'=memory


* ravel()<br>
 **(numpy.ravel(a,order='c'))**

In [13]:
import numpy as np
#flatten
fl=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print('ndim & shape: ',fl.ndim, fl.shape)
print('C - row: ',fl.flatten())
print('F - col: ',fl.flatten(order='F'))
print('A - fortran : ',fl.flatten(order='A'))
print('K - memory: ',fl.flatten(order='K'))

#ravel()--Return a contiguous flattened array.
print('Ravel method: ',fl.ravel())

print('Using Reshape method to flatten: ',fl.reshape(-1))

ndim & shape:  3 (2, 2, 3)
C - row:  [ 1  2  3  3  4  5  6  7  8  9 10 11]
F - col:  [ 1  6  3  9  2  7  4 10  3  8  5 11]
A - fortran :  [ 1  2  3  3  4  5  6  7  8  9 10 11]
K - memory:  [ 1  2  3  3  4  5  6  7  8  9 10 11]
Ravel method:  [ 1  2  3  3  4  5  6  7  8  9 10 11]
Using Reshape method to flatten:  [ 1  2  3  3  4  5  6  7  8  9 10 11]


### **Dimension Shuffling**
* transpose()<br>
 **(numpy.transpose(array, axes=None))**--axes-(1,0) or (0,1)


* swapaxes()<br>
 **(numpy.swapaxes(array,axis1,axis2))**

In [14]:
#transpose
import numpy as np
tran=np.arange(1,11).reshape(5,2)
print('Before Transpose: \n',tran)
print('After Transpose: \n',tran.transpose())

#axes 0:2, axes 1:3, axes 2:4
trans=np.arange(1,25).reshape(2,3,4)
print('\nBefore Transpose: \n',trans)
print('After Transpose: \n',trans.transpose(1,2,0))

Before Transpose: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
After Transpose: 
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]

Before Transpose: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
After Transpose: 
 [[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [15]:
#swapaxes()--only use for two dimension
swap=np.array([[1,2],[4,5]])
swap[:,[0, 1]] = swap[:,[1, 0]]
print(swap.shape)
print(swap)

(2, 2)
[[2 1]
 [5 4]]


In [16]:
xyz = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print('Shape: ',xyz.shape)
print('swap of axis 2: \n',np.swapaxes(xyz,0,2))
print('swap of axis 1: \n',np.swapaxes(xyz,0,1))

Shape:  (2, 2, 2)
swap of axis 2: 
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
swap of axis 1: 
 [[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


### **Joining array**
* concatenate()<br>
 **(numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind"))**--a1, a2,sequence of array_like


* vstack()<br>
 **(numpy.vstack(tup))**--Stack arrays in sequence vertically (row wise).
 

* hstack()<br>
 **(numpy.hstack(tup))**--Stack arrays in sequence horizontally (column wise).

In [17]:
#concatenate
import numpy as np
con1=np.arange(10)
con2=np.arange(0,6)
con3=np.zeros(16)
print('Concatenate the two range of con1 & con2: ',np.concatenate((con1,con2)))
print('outndarray, optional: ',np.concatenate((con1,con2),out=con3))
print('Axis is None, arrays are flattened before use. Default is 0: ',np.concatenate((con1,con2.T),axis=0))


Concatenate the two range of con1 & con2:  [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5]
outndarray, optional:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0. 1. 2. 3. 4. 5.]
Axis is None, arrays are flattened before use. Default is 0:  [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5]


In [18]:
#vstack
import numpy as np
s1 = np.array([1, 2, 3])
s2 = np.array([4, 5, 6])
s3 = np.array([[1], [2], [3]])
s4 = np.array([[4], [5], [6]])
print('vstack:s1 & s2 \n',np.vstack((s1,s2))) 
print('vstack:s3 & s4 \n',np.vstack((s3,s4))) 
print('hstack:s1 & s2 \n',np.hstack((s1,s2))) 
print('hstack:s3 & s4 \n',np.hstack((s3,s4)))

vstack:s1 & s2 
 [[1 2 3]
 [4 5 6]]
vstack:s3 & s4 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
hstack:s1 & s2 
 [1 2 3 4 5 6]
hstack:s3 & s4 
 [[1 4]
 [2 5]
 [3 6]]


### **Splitting array**
* split()<br>
 **(numpy.split(ary, indices_or_sections, axis=0))**--Split array into a list of multiple sub-arrays of equal size.


* vsplit()<br>
 **(numpy.vsplit(ary, indices_or_sections))**--Split array into multiple sub-arrays vertically (row wise).
 

* hsplit()<br>
 **(numpy.hsplit(ary, indices_or_sections))**--Split array into multiple sub-arrays horizontally (column wise).
 

* dsplit()<br>
 **(numpy.dsplit(ary, indices_or_sections))**--Split array into multiple sub-arrays along the 3rd axis (depth).

In [19]:
import numpy as np
#split()
sp1= np.arange(0,9)
print('Split the range of 3: ',np.split(sp1,3))
print('Split the range of given list: ',np.split(sp1,[3,5,8]))

vsp1=np.arange(16.0).reshape(4, 4)

#vsplit()
print('vsplit: \n',np.vsplit(vsp1,2))

#hsplit()
print('hsplit: \n',np.hsplit(vsp1,2))

#dsplit()--It works only for 3 or more dim
dsp=np.arange(16.0).reshape(2, 2, 4)
print('dsplit: \n',np.dsplit(dsp,2))

Split the range of 3:  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Split the range of given list:  [array([0, 1, 2]), array([3, 4]), array([5, 6, 7]), array([8])]
vsplit: 
 [array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
hsplit: 
 [array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
dsplit: 
 [array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


### **Add/Remove elements**
* Insert()<br>
 **(numpy.insert(arr, obj, values, axis=None))**--Insert values along the given axis before the given indices.


* Append()<br>
 **(numpy.append(arr, values, axis=None))**--Append values to the end of an array.
 

* Delete()<br>
 **(numpy.delete(arr, obj, axis=None))**

In [20]:
import numpy as np
#insert()
ins = np.array([[1, 1], [2, 2], [3, 3]])
print('printing values: \n',ins)
print('Insert 1 & 5: \n',np.insert(ins, 1, 5))
print('Insert 1 & 5 in axis 1: \n',np.insert(ins, 1, 5, axis=1))

#append()
print('Append 1D to 2D: \n',np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]))
print('Append 2D to 2D: \n',np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0))

#delete()
dele=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print('Delete the list of 1,3,5: \n',np.delete(dele, [1,3,5], None))
print('Delete the 2 element of ins: \n',np.delete(ins,2, None))
print('Delete the 1 row of ins: \n',np.delete(ins,1,axis=0)) #axis=0 Horizantal
print('Delete the 1 col of ins: \n',np.delete(ins,1,axis=1)) #axis=1 Vertical

printing values: 
 [[1 1]
 [2 2]
 [3 3]]
Insert 1 & 5: 
 [1 5 1 2 2 3 3]
Insert 1 & 5 in axis 1: 
 [[1 5 1]
 [2 5 2]
 [3 5 3]]
Append 1D to 2D: 
 [1 2 3 4 5 6 7 8 9]
Append 2D to 2D: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Delete the list of 1,3,5: 
 [ 1  3  5  7  8  9 10 11 12]
Delete the 2 element of ins: 
 [1 1 2 3 3]
Delete the 1 row of ins: 
 [[1 1]
 [3 3]]
Delete the 1 col of ins: 
 [[1]
 [2]
 [3]]


## Matrix
* Matrix Addition
* Matrix Multiplication (* array multiply, dot(.) Matrix multiply)
* Matrix Class  **(numpy.matrix (data, dtype=None, copy=True))** <br>

**Rule:** <br>
    1). Matrix can be created using string notation <br>
    2). Matrix objects are always 2D <br>
    3). Can use * for matrix multiply <br>

In [38]:
import numpy as np

#Matrix Addition
maa=np.array([[1,2],[3,4]])
mab=np.array([[10,20],[30,40]])
print('Matrix Addition(+): \n',maa+mab)
print('Matrix Sutraction(-): \n',maa-mab)

#Matrix Multiplication
print('Array Multiplication(*): \n',maa*mab)
print('Matrix Multiplication(.dot()): \n',maa.dot(mab))

#Matrix class
mca=np.matrix("1 2;3 4", dtype='f')
print('Matrix class: \n',mca)
mcb=np.matrix([[10,20],[30,40]], dtype='i')
print('Matrix class: \n',mcb)
print('Matrix Transpose: \n',mcb.T)

Matrix Addition(+): 
 [[11 22]
 [33 44]]
Matrix Sutraction(-): 
 [[ -9 -18]
 [-27 -36]]
Array Multiplication(*): 
 [[ 10  40]
 [ 90 160]]
Matrix Multiplication(.dot()): 
 [[ 70 100]
 [150 220]]
Matrix class: 
 [[1. 2.]
 [3. 4.]]
Matrix class: 
 [[10 20]
 [30 40]]
Matrix Transpose: 
 [[10 30]
 [20 40]]


## Linear algebra module
**Syntax**: numpy.linalg
   * Invert
   * Power
   * Linear equation
   * Determinants of matrix

In [41]:
import numpy as np
#invert()- Inverse the given square matrix.
#numpy.linalg.inv(a)
inv_a=np.array([[1,2],[3,4]])
print(np.linalg.inv(inv_a))

#Explanation:
'''a=([[a,b],[c,d]])
   a=1/ad-bc ([[d,-b],[-c,a]]) '''

[[-2.   1. ]
 [ 1.5 -0.5]]


'a=([[a,b],[c,d]])\n   a=1/ad-bc ([[d,-b],[-c,a]]) '

In [48]:
import numpy as np
#power()- a (matrix), n (power)
#numpy.linalg.matrix_power(a,n)
pow_a=np.array([[1,2],[3,4]])
print('using np.dot(a,a): \n',np.dot(pow_a,pow_a))
print('n>0 Power is repeated: \n',np.linalg.matrix_power(pow_a,2))
print('n=0 Identity matrix: \n',np.linalg.matrix_power(pow_a,0))
print('n<0 Inverese is computed & raised to its abs value: \n',np.linalg.matrix_power(pow_a,-2))

#Explanation:
'''A**2=A.A , A**3=A.A.A ==>(n>0)
   A**-1=A.A ==>(n<0)'''

using np.dot(a,a): 
 [[ 7 10]
 [15 22]]
n>0 Power is repeated: 
 [[ 7 10]
 [15 22]]
n=0 Identity matrix: 
 [[1 0]
 [0 1]]
n<0 Inverese is computed & raised to its abs value: 
 [[ 5.5  -2.5 ]
 [-3.75  1.75]]


'A**2=A.A , A**3=A.A.A ==>(n>0)\n   A**-1=A.A ==>(n<0)'

In [53]:
import numpy as np
#linear equation()- To find out the unknown values
#numpy.linalg.solve(a,b)
lin_a=np.array([[3,1],[1,2]])
lin_b=np.array([9,8])
print('Linear equation lin_a & lin_b: \n',np.linalg.solve(lin_a,lin_b))
lin_aa=np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
lin_bb=np.array([13,13,26])
print('Linear equation lin_aa & lin_bb: \n',np.linalg.solve(lin_aa,lin_bb))

#Explanation:
'''AX=B (A-Matrix, X-Variable, B-Constant) 
   3x+y=9, x+2y=8 ==> a=([[3,1],[1,2]]) b=([9,8])'''

Linear equation lin_a & lin_b: 
 [2. 3.]
Linear equation lin_aa & lin_bb: 
 [2. 3. 1.]


'AX=B (A-Matrix, X-Variable, B-Constant) \n   3x+y=9, x+2y=8 ==> a=([[3,1],[1,2]]) b=([9,8])'

In [56]:
import numpy as np
#determinant of a matrix
#numpy.linalg.det(a)
det_a=np.array([[1,2],[3,4]])
print(round(np.linalg.det(det_a)))

#Explanation:
'''A=([[a,b],[c,d]])=ad - bc
   A=([[1,2],[3,4]])=4-6 = -2'''

-2


'A=([[a,b],[c,d]])=ad - bc\n   A=([[1,2],[3,4]])=4-6 = -2'